//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YS.Knife.Generator.UnitTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YS.Knife.Generator.UnitTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using YS.Knife;
        ///namespace ConsoleApp2
        ///{
        ///    partial class Class1
        ///    {
        ///        [AutoNotify]
        ///        private int _age;
        ///
        ///    }
        ///}.
        /// </summary>
        internal static string AutoNotifyHapplyCase {
            get {
                return ResourceManager.GetString("AutoNotifyHapplyCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.ComponentModel;
        ///namespace ConsoleApp2
        ///{
        ///    partial class Class1 : System.ComponentModel.INotifyPropertyChanged
        ///    {
        ///        public event PropertyChangedEventHandler PropertyChanged;
        ///
        ///        public int Age 
        ///        {
        ///            get 
        ///            {
        ///                return this._age;
        ///            }
        ///            set
        ///            {
        ///                if(this._age != value)
        ///                {
        ///                    this._age = value;
        ///                    this.PropertyChanged?.Invoke(this, ne [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AutoNotifyHapplyExpected {
            get {
                return ResourceManager.GetString("AutoNotifyHapplyExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using YS.Knife;
        ///namespace ConsoleApp2
        ///{
        ///    public  class Class4
        ///    {
        ///        partial class Class5
        ///        {
        ///            [AutoNotify]
        ///            private int _age;
        ///            [AutoNotify]
        ///            private int _age2;
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string AutoNotifyNestedClass {
            get {
                return ResourceManager.GetString("AutoNotifyNestedClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.ComponentModel;
        ///    namespace ConsoleApp2
        ///    {
        ///        partial class Class4
        ///        {
        ///            partial class Class5 : System.ComponentModel.INotifyPropertyChanged
        ///            {
        ///                public event PropertyChangedEventHandler PropertyChanged;
        ///    
        ///                public int Age 
        ///                {
        ///                    get 
        ///                    {
        ///                        return this._age;
        ///                    }
        ///                    set
        ///                    {
        ///                [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AutoNotifyNestedClassExpected {
            get {
                return ResourceManager.GetString("AutoNotifyNestedClassExpected", resourceCulture);
            }
        }
    }
}
